### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by dlewand691** [vecta-io/nanosvg#2]
Where is the API key found?

**Comment by neel-radica** [comment]
Hi @dlewand691 we have emailed you with the link to get the API key. Please give it a try again, thank you.

**Comment by dlewand691** [comment]
Thanks. I got the updated email but now when I go to sign up, I never receive the verification email to confirm my account. Have tried clicking the resend button and also checked my junk folder.

**Comment by neel-radica** [comment]
Hi @dlewand691 . Could you please try signing up using your dlewandowski38@yahoo.com mail and see if it works? If needed, we could reset your email so that you could sign up again. Please do let us know. Thanks.

**Comment by dlewand691** [comment]
Hey @neel-radica 
THAT WORKED! THANK YOU! I'm able to generate an API key now :-) Yay!

**Comment by neel-radica** [comment]
Great. Thanks for trying out and do let us know if you face any issues.

**Comment by dlewand691** [comment]
Sorry, closed too soon without fully testing. No API key is generated but can access my account.

**Comment by neel-radica** [comment]
Sorry about that. Could you please give it a try again?

**Comment by dlewand691** [comment]
Works! Thanks again for the quick help!

**Comment by neel-radica** [comment]
No problem. Thanks for trying out and do let us know if you face any issues.

**Comment by alexanderyarm** [comment]
Guys your service is great! but I couldn't find any place where I can get an API key

**Comment by raoradica** [comment]
Hi Alex,

It's great to hear that. Unfortunately we have deprecated the CLI tool for nanosvg using the API key. This is because the CLI tool does compression on the cloud which is slower that we have initially expected.

Hence, we are working another solution that does offline compression reliably and fast. Currently we are at the testing phase before the release which is expected to be by end of this month or early of next month latest.

For more info, please do not hesitate to contact us at hello@vecta.io

**Comment by janosh** [comment]
What's the current status? Is there a way now to obtain an API key to do either online or offline compression?
